### ISSUE TITLE
Add sample: Azure Active Directory + Reactive

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/spring-boot-application-with-azure-active-directory#6]
Refs: https://docs.spring.io/spring-security/reactive/index.html

**Comment by chenrujun** [comment]
Closing this issue, use this one instead: https://github.com/Azure/azure-sdk-for-java/issues/25817

**Comment by dougnob** [comment]
Hi @chenrujun,

I have seen multiple issues discussing the topic of spring-cloud-azure-starter-active-directory & webflux. But I can't seem to find a definitive answer to my question (apologies if I missed it). 
Is support now provided for the reactive stack? Is there a sample somewhere in this repository or elsewhere?

Thanks for your help,

**Comment by chenrujun** [comment]
Hi, @dougnob 

Thanks for reaching out.

> Is support now provided for the reactive stack?

No, it's not supported. Now we use this issue to track: https://github.com/Azure/azure-sdk-for-java/issues/21290

**Comment by dougnob** [comment]
@chenrujun,
Understood, thanks for the quick reply.
